### PR TITLE
Add .jscsrc to repo

### PR DESCRIPTION
**Pull request by alexmckenley**
@deini #gamechanger

### CODE REVIEW

**Comment by deini** [comment]
@alexmckenley Lol we have 2 separate PRs for the same thing xD

**Comment by alexmckenley** [comment]
and we both used hashtags in the description

**Comment by alexmckenley** [comment]
Lets see which one ray merges in

**Comment by deini** [comment]
lol

**Comment by deini** [comment]
This one has `requireSpaceBeforeBinaryOperators` declared twice, pick mine ray!

**Comment by alexmckenley** [comment]
pinging @malucky for visibility

**Pull request closed without merging**
