### PR TITLE
Added event service to ammo app

### PR DESCRIPTION
**Pull request by alexmckenley**
pinging @malucky @deini

### CODE REVIEW

**Comment by alexmckenley** [comment]
:heavy_plus_sign:  @ssalazars

**Comment by deini** [comment]
Beautiful. http://i.gifly.com/media_gifly/q/Q/c/C/b/qQcC.gif

**Comment by deini** [comment]
We should start commenting out our code to be https://github.com/angular/dgeni compatible

**Comment by alexmckenley** [comment]
Does it do something special for us? If anything, I was thinking we should use jsdoc: https://github.com/johnpapa/angularjs-styleguide#comments

**Comment by deini** [comment]
Yep, they are the same. dgeni supports jsDoc.

**Comment by alexmckenley** [comment]
@deini let me know if you see anything else.

**Comment by deini** [comment]
Good stuff :100:

**Pull request merged**
