### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by malucky**
docs for dev not updated. the previous update was made to master branch

@alexmckenley @deini

### CODE REVIEW

**Comment by deini** [comment]
What error is `.ammo` giving you? We need it

**Comment by malucky** [comment]
oh ok...i think i just had to update vagrant. I thought we don't need it because the updated doc on master doesn't have it. i'll add it back in

**Comment by deini** [comment]
So `.ammo` runs the vagrant task for you, alex has to do it manually because he's coding in his gaming pc (windows)

**Comment by deini** [comment]
So we don't need point 8. Maybe specify the difference if you are in windows? /discuss pinging @alexmckenley

**Comment by malucky** [comment]
ok sweet, well let's just leave it as is then

**Comment by alexmckenley** [comment]
Just for the record I think everything works fine on windows... I just forgot we made the ./ammo script, so I never tried it.

**Comment by alexmckenley** [comment]
I'm sure it works on windows as well

**Pull request closed without merging**
